services:
  - type: web
    name: physics-courses
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn physics_courses.wsgi_production:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: physics-courses.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: physics-courses-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: physics-courses-db
    databaseName: physics_courses
    user: physics_courses_user
    plan: free
