# Generated by Django 5.2.5 on 2025-08-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(upload_to='courses/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='nobellaureate',
            name='photo',
            field=models.FileField(upload_to='laureates/', verbose_name='Фотография'),
        ),
    ]
